---
title: "Design - Heteroscedastic"
date: today
date-format: long
format: 
  gfm:
    preview-mode: raw
    html-math-method: 
      method: webtex
      url: https://latex.codecogs.com/png.image?%5Cbg_black&space;
---

**Chi-Kuang Yeh**  
*McGill University and University of Waterloo*  

## Description

This is the repo to compute regression model with heteroscedastic error.

## The Model

$$
  y(x)=f^\top(x) \beta + e/\sqrt{\lambda(x)} = \sum_{i=1}^p f_i(x) \beta_i + e / \sqrt{\lambda(x) } 
$$

## Contact or Suggestions

If you encounter any issues, please contact me [Chi-Kuang Yeh](https://chikuang.github.io/) at [chi-kuang.yeh@uwaterloo.ca](mailto:chi-kuang.yeh@uwaterloo.ca) or [chi-kuang.yeh@mail.mcgill.ca](mailto:chi-kuang.yeh@mail.mcgill.ca).  

## References

1. Chen, R.-B., Wong, W.K., & Li, K.-Y. (2008) [Optimal minimax designs over a prespecified interval in a heteroscedastic polynomial model](https://www.sciencedirect.com/science/article/pii/S0167715208000588?casa_token=CSYGIaqcSycAAAAA:xH69BebDGq6GYitdc3m28CCcE8AFU8a0qL8DbHifzMxgyAwuP-7MBltelbBokw9QiVl8wz9bsjQ). *Statistics & Probability Letters* 78, 1914--1921.

2. Wong, W.K. (1994). [G-optimal designs for multi-factor experiments with heteroscedastic errors](https://www.sciencedirect.com/science/article/pii/0378375894901465). *Journal of Statistical Planning and Inference*, 40, 127--133.

3. Wong, W.K. & Cook, R.D. (1993). [Heteroscedastic G‐optimal designs](https://www.jstor.org/stable/2345999). *Journal of the Royal Statistical Society, Series B*, 55, 871--880.

## TODO

+ [ ] \(G\)-optimality
+ [ ] \(E\)-optimality]